<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="contact">
	<div class="btn-group">
	   <a class="btn" title="<?php _e('Add Department'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="icon-list-alt"></i> <?php _e('Add Department'); ?></a>
	</div>
	<h3><?php _e('List of departments'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Email'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($departments as $department) { ?>
		<tr>
			<td><?php echo $this->escape($department['id']); ?></td>
			<td><?php echo $this->escape($department['title']); ?></td>
			<td><?php echo $this->escape($department['email']); ?></td>
			<td>
				<div class="btn-group">
					<a class="btn" title="<?php _e('Messages'); ?>" href="#"><i class="icon-eye-open"></i> <?php _e('Messages'); ?></a>
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $department['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $department['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
				</div>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>