<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="contact">
   <?php if(isset($department)) { ?>
	<p>
		<a class="btn-primary" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="icon-arrow-left"></i> <?php _e('Back'); ?></a>
	</p>
   <?php } ?>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Subject'); ?></th>
			<th><?php _e('Department'); ?></th>
			<th><?php _e('Author'); ?></th>
			<th><?php _e('Create'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($messages as $message) { ?>
		<tr>
			<td><?php echo $this->escape($message['id']); ?></td>
			<td><?php if($message['answered']) { ?><span class="label label-success"><?php _e('Answered'); ?></span> <?php } ?><?php echo $this->escape($message['subject']); ?></td>
			<td><a title="<?php echo $this->escape($message['departmenttitle']); ?>" href="<?php echo $this->url('', array('action' => 'index', 'department' => $this->escape($message['department']))); ?>"><?php echo $this->escape($message['departmenttitle']); ?></a></td>
			<td><?php echo $this->escape($message['name']); ?> ( <?php echo $this->escape($message['user']['identity']); ?> <?php echo $this->escape($message['user']['name']); ?> )</td>
			<td><?php echo $this->escape($message['time_create']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $this->url('', array('action' => 'view', 'id' => $message['id'])); ?>"><i class="fa fa-eye"></i> <?php _e('View'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Reply'); ?>" href="<?php echo $this->url('', array('action' => 'reply', 'id' => $message['id'])); ?>"><i class="fa fa-reply"></i> <?php _e('Reply'); ?></a>
				<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $message['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>