<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt New BSD License
 */

/**
 * @author Hossein Azizabadi <azizabadi@faragostaresh.com>
 */
return array(
    'category' => array(
        array(
            'title' => __('Admin'),
            'name' => 'admin'
        ),
        array(
            'title' => __('HomePage'),
            'name' => 'home'
        ),
        array(
            'title' => __('Form'),
            'name' => 'form'
        ),
        array(
            'title' => __('Google Map'),
            'name' => 'gmap'
        ),
        array(
            'title' => __('Social Network'),
            'name' => 'social'
        ),
    ),
    'item' => array(
        // Admin
        'admin_perpage' => array(
            'category' => 'admin',
            'title' => __('Perpage'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'number_int',
            'value' => 50
        ),
        // Home
        'homepage' => array(
            'title' => __('Homepage'),
            'description' => ' ',
            'edit' => array(
                'type' => 'select',
                'options' => array(
                    'options' => array(
                        'from' => __('Default form'),
                        'list' => __('List of Departments'),
                    ),
                ),
            ),
            'filter' => 'string',
            'value' => 'from',
            'category' => 'home',
        ),
        'breadcrumbs' => array(
            'title' => __('Show breadcrumbs'),
            'description' => '',
            'value' => 1,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'home',
        ),
        'toptext' => array(
            'title' => __('Top text'),
            'description' => '',
            'edit' => 'textarea',
            'value' => '',
            'category' => 'home',
        ),
        'bottomtext' => array(
            'title' => __('Bottom text'),
            'description' => '',
            'edit' => 'textarea',
            'value' => '',
            'category' => 'home',
        ),
        'sidetext' => array(
            'title' => __('Side text'),
            'description' => '',
            'edit' => 'textarea',
            'value' => '',
            'category' => 'home',
        ),
        'finishtext' => array(
            'title' => __('Finish text'),
            'description' => '',
            'edit' => 'textarea',
            'value' => '',
            'category' => 'home',
        ),
        // Form
        'default_department' => array(
            'title' => __('Default department'),
            'description' => '',
            'value' => 1,
            'edit' => 'Module\Contact\Form\Element\Department',
            'filter' => 'number_int',
            'category' => 'form',
        ),
        'show_department' => array(
            'title' => __('show Department'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'show_organization' => array(
            'title' => __('show Organization'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'required_organization' => array(
            'title' => __('required Organization'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'show_homepage' => array(
            'title' => __('show Homepage'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'required_homepage' => array(
            'title' => __('required Homepage'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'show_location' => array(
            'title' => __('show Location'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'required_location' => array(
            'title' => __('required Location'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'show_phone' => array(
            'title' => __('show Phone'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'required_phone' => array(
            'title' => __('required Phone'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'show_address' => array(
            'title' => __('show Address'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'required_address' => array(
            'title' => __('required Address'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        'captcha' => array(
            'title' => __('Use captcha'),
            'description' => __('Captcha just use for gust'),
            'value' => 1,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'form',
        ),
        // social
        'social_twitter' => array(
            'title' => __('Twitter account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_twitter_icon' => array(
            'title' => __('Twitter icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_facebook' => array(
            'title' => __('Facebook account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_facebook_icon' => array(
            'title' => __('Facebook icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_google' => array(
            'title' => __('Google plus account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_google_icon' => array(
            'title' => __('Google plus icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_youtube' => array(
            'title' => __('YouTube account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_youtube_icon' => array(
            'title' => __('YouTube icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_pinterest' => array(
            'title' => __('Pinterest account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_pinterest_icon' => array(
            'title' => __('Pinterest icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_linkedin' => array(
            'title' => __('LinkedIn account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_linkedin_icon' => array(
            'title' => __('LinkedIn icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_github' => array(
            'title' => __('Github account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_github_icon' => array(
            'title' => __('Github icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_instagram' => array(
            'title' => __('Instagram account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_instagram_icon' => array(
            'title' => __('Instagram icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_tumblr' => array(
            'title' => __('Tumblr account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_tumblr_icon' => array(
            'title' => __('Tumblr icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_trello' => array(
            'title' => __('Trello account'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_trello_icon' => array(
            'title' => __('Trello icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_rss' => array(
            'title' => __('Rss link'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        'social_rss_icon' => array(
            'title' => __('Rss icon'),
            'description' => __('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'social',
        ),
        // Gmap
        'gmap_show' => array(
            'title' => __('Show Google Map'),
            'description' => '',
            'value' => 0,
            'filter' => 'number_int',
            'edit' => 'checkbox',
            'category' => 'gmap',
        ),
        'gmap_longitude' => array(
            'title' => __('Longitude'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'gmap',
        ),
        'gmap_latitude' => array(
            'title' => __('Latitude'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'gmap',
        ),
        'gmap_zoon' => array(
            'title' => __('Zoon'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '16',
            'category' => 'gmap',
        ),
        'gmap_title' => array(
            'title' => __('Title'),
            'description' => '',
            'edit' => 'text',
            'filter' => 'string',
            'value' => '',
            'category' => 'gmap',
        ),
    ),
);