<?php
/**
 * Pi Engine (http://pialog.org)
 *
 * @link            http://code.pialog.org for the Pi Engine source repository
 * @copyright       Copyright (c) Pi Engine http://pialog.org
 * @license         http://pialog.org/license.txt New BSD License
 */

/**
 * @author Hossein Azizabadi <azizabadi@faragostaresh.com>
 */
return array(
    'category' => array(
        array(
            'title'  => _a('Admin'),
            'name'   => 'admin'
        ),
        array(
            'title'  => _a('HomePage'),
            'name'   => 'home'
        ),
        array(
            'title'  => _a('SEO texts'),
            'name'   => 'seo'
        ),
        array(
            'title'  => _a('Form'),
            'name'   => 'form'
        ),
        array(
            'title'  => _a('Google Map'),
            'name'   => 'gmap'
        ),
        /* array(
            'title'  => _a('Social Network'),
            'name'   => 'social'
        ), */
    ),
    'item' => array(
        // Admin
        'admin_perpage' => array(
            'category'     => 'admin',
            'title'        => _a('Perpage'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'number_int',
            'value'        => 50
        ),
        // Home
        'homepage' => array(
            'title'        => _a('Homepage'),
            'description'  => ' ',
            'edit'         => array(
                'type' => 'select',
                'options' => array(
                    'options' => array(
                        'from' => _a('Default form'),
                        'list' => _a('List of Departments'),
                    ),
                ),
            ),
            'filter'       => 'string',
            'value'        => 'from',
            'category'     => 'home',
        ),
        'breadcrumbs' => array(
            'title'        => _a('Show breadcrumbs'),
            'description'  => '',
            'value'        => 1,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'home',
        ),
        'toptext' => array(
            'title'        => _a('Top text'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => '',
            'category'     => 'home',
        ),
        'bottomtext' => array(
            'title'        => _a('Bottom text'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => '',
            'category'     => 'home',
        ),
        'sidetext' => array(
            'title'        => _a('Side text'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => '',
            'category'     => 'home',
        ),
        'finishtext' => array(
            'title'        => _a('Finish text'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => _a('Message correctly Send, a confirmation has just been sent to you by email'),
            'category'     => 'home',
        ),
        // SEO
        'index_seo_title' => array(
            'title'        => _a('SEO title for index page'),
            'description'  => '',
            'edit'         => 'text',
            'value'        => '',
            'category'     => 'seo',
        ),
        'index_seo_description' => array(
            'title'        => _a('SEO description for index page'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => _a('Contact us form'),
            'category'     => 'seo',
        ),
        'index_seo_keywords' => array(
            'title'        => _a('SEO keywords for index page'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => _a('contact,us,form'),
            'category'     => 'seo',
        ),
        'list_seo_title' => array(
            'title'        => _a('SEO title for list page'),
            'description'  => '',
            'edit'         => 'text',
            'value'        => _a('List of departments'),
            'category'     => 'seo',
        ),
        'list_seo_description' => array(
            'title'        => _a('SEO description for list page'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => _a('Select Department Form contact us'),
            'category'     => 'seo',
        ),
        'list_seo_keywords' => array(
            'title'        => _a('SEO keywords for list page'),
            'description'  => '',
            'edit'         => 'textarea',
            'value'        => _a('select,department,form,contact,us'),
            'category'     => 'seo',
        ),
        // Form
        'default_department' => array(
            'title'        => _a('Default department'),
            'description'  => '',
            'value'        => 1,
            'edit'         => 'Module\Contact\Form\Element\Department',
            'filter'       => 'number_int',
            'category'     => 'form',
        ),
        'show_title' => array(
            'title'        => _a('show title'),
            'description'  => '',
            'value'        => 1,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'show_department' => array(
            'title'        => _a('show Department'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'show_organization' => array(
            'title'        => _a('show Organization'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'required_organization' => array(
            'title'        => _a('required Organization'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'show_homepage' => array(
            'title'        => _a('show Homepage'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'required_homepage' => array(
            'title'        => _a('required Homepage'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'show_location' => array(
            'title'        => _a('show Location'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'required_location' => array(
            'title'        => _a('required Location'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'show_phone' => array(
            'title'        => _a('show Phone'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'required_phone' => array(
            'title'        => _a('required Phone'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'show_address' => array(
            'title'        => _a('show Address'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'required_address' => array(
            'title'        => _a('required Address'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        'captcha' => array(
            'title'        => _a('Use captcha'),
            'description'  => _a('Captcha just use for gust'),
            'value'        => 1,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'form',
        ),
        // social
        /* 'social_twitter' => array(
            'title'        => _a('Twitter account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_twitter_icon' => array(
            'title'        => _a('Twitter icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_facebook' => array(
            'title'        => _a('Facebook account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_facebook_icon' => array(
            'title'        => _a('Facebook icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_google' => array(
            'title'        => _a('Google plus account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_google_icon' => array(
            'title'        => _a('Google plus icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_youtube' => array(
            'title'        => _a('YouTube account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_youtube_icon' => array(
            'title'        => _a('YouTube icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_pinterest' => array(
            'title'        => _a('Pinterest account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_pinterest_icon' => array(
            'title'        => _a('Pinterest icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_linkedin' => array(
            'title'        => _a('LinkedIn account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_linkedin_icon' => array(
            'title'        => _a('LinkedIn icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_github' => array(
            'title'        => _a('Github account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_github_icon' => array(
            'title'        => _a('Github icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_instagram' => array(
            'title'        => _a('Instagram account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_instagram_icon' => array(
            'title'        => _a('Instagram icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_tumblr' => array(
            'title'        => _a('Tumblr account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_tumblr_icon' => array(
            'title'        => _a('Tumblr icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_trello' => array(
            'title'        => _a('Trello account'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_trello_icon' => array(
            'title'        => _a('Trello icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_rss' => array(
            'title'        => _a('Rss link'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ),
        'social_rss_icon' => array(
            'title'        => _a('Rss icon'),
            'description'  => _a('Set icon url (Uploaded on your host) or leave empty to use default icon'),
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'social',
        ), */
        // Gmap
        'gmap_show' => array(
            'title'        => _a('Show Google Map'),
            'description'  => '',
            'value'        => 0,
            'filter'       => 'number_int',
            'edit'         => 'checkbox',
            'category'     => 'gmap',
        ),
        'gmap_position' => array(
            'title'        => _a('Position'),
            'description'  => ' ',
            'edit'         => array(
                'type' => 'select',
                'options' => array(
                    'options' => array(
                        'side' => _a('Side'),
                        'top' => _a('Top'),
                    ),
                ),
            ),
            'filter'       => 'string',
            'value'        => 'side',
            'category'     => 'gmap',
        ),
        'gmap_latitude' => array(
            'title'        => _a('Latitude'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'gmap',
        ),
        'gmap_longitude' => array(
            'title'        => _a('Longitude'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'gmap',
        ),
        'gmap_zoon' => array(
            'title'        => _a('Zoon'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '16',
            'category'     => 'gmap',
        ),
        'gmap_title' => array(
            'title'        => _a('Title'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '',
            'category'     => 'gmap',
        ),
        'gmap_height' => array(
            'title'        => _a('Height'),
            'description'  => '',
            'edit'         => 'text',
            'filter'       => 'string',
            'value'        => '300',
            'category'     => 'gmap',
        ),
    ),
);