<?php
// Set header css and scripts
$this->css($this->assetModule('css/front.css'));

// Set html class
if (!empty($config['sidetext']) || ($config['map_show'] && $config['map_position'] == 'side')) {
    $class = 'col-md-7';
} else {
    $class = 'col-md-12';
}
?>
<div class="clearfix row">
    <?php if ($config['gmap_show'] && $config['gmap_position'] == 'top') { ?>
        <?php
        ob_start();
        include('partial/contact-wide-header.phtml');
        $wideContent = ob_get_clean();
        echo $this->wideContent($wideContent, $module);
        ?>
    <?php } ?>
    <?php if ($config['show_title']) { ?>
        <div class="page-header contact-title">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
    <?php } ?>
    <div class="<?php echo $class; ?>">
        <?php if (!empty($config['toptext'])) { ?>
            <div class="clearfix contact-toptext row">
                <?php echo $config['toptext']; ?>
            </div>
        <?php } ?>
        <?php if ($allowSubmit) { ?>
            <div class="contact-form">
                <?php echo $this->form($form, 'vertical'); ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-danger">
                <?php echo sprintf(
                    __('You allowed to send next contact request after %s min than your last submitted time'),
                    $config['block_time']
                ); ?>
            </div>
        <?php } ?>
    </div>
    <?php if (!empty($config['sidetext']) || ($config['map_show'] && $config['map_position'] == 'side')) { ?>
        <div class="col-md-5">
            <?php if (!empty($config['sidetext'])) { ?>
                <div class="clearfix contact-sidetext">
                    <?php echo $config['sidetext']; ?>
                </div>
            <?php } ?>
            <?php if ($config['map_show'] && $config['map_position'] == 'side') { ?>
                <?php if ($mapSetting['type'] == 'google') {
                    echo $this->googleMap($mapSetting['location'], $mapSetting['key'], 'point', $mapSetting['option']);
                } elseif ($mapSetting['type'] == 'osm') {
                    echo $this->leaflet($mapSetting['params']);
                } ?>
            <?php } ?>
        </div>
    <?php } ?>
    <?php if (!empty($config['bottomtext'])) { ?>
        <div class="clearfix contact-bottomtext col-md-12">
            <?php echo $config['bottomtext']; ?>
        </div>
    <?php } ?>
</div>