<?php
$this->css($this->assetModule('css/front.css'));
// Load google map
if ($config['gmap_show']) {
    $locations = [
        'latitude'  => $config['gmap_latitude'],
        'longitude' => $config['gmap_longitude'],
        'zoom'      => $config['gmap_zoon'],
        'title'     => $config['gmap_title'],
    ];

    $option = [
        'mapTypeId' => $config['gmap_type'],
    ];
}
?>
<div class="clearfix">
    <?php if ($config['gmap_show'] && $config['gmap_position'] == 'top') { ?>

        <?php
        ob_start();
        include('partial/contact-wide-header.phtml');
        $wideContent = ob_get_clean();
        echo $this->wideContent($wideContent, $module);
        ?>
    <?php } ?>
    <?php if ($config['show_title']) { ?>
        <div class="page-header contact-title">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
    <?php } ?>
    <?php if (!empty($config['sidetext']) || ($config['gmap_show'] && $config['gmap_position'] == 'side')) {
        $class = 'col-md-7';
    } else {
        $class = 'col-md-12';
    } ?>
    <div class="<?php echo $class; ?>">
        <?php if (!empty($config['toptext'])) { ?>
            <div class="clearfix contact-toptext">
                <?php echo $config['toptext']; ?>
            </div>
        <?php } ?>
        <?php if (isset($finish) && $finish == 1) { ?>
            <div class="alert alert-success">
                <?php echo $finishText; ?>
            </div>
            <p><a class="btn btn-success" title="<?php _e('Back'); ?>" href="<?php Pi::url($this->url('', ['action' => 'index'])); ?>"><?php _e('Back'); ?></a>
            </p>
        <?php } else { ?>
            <div class="contact-form">
                <?php echo $this->form($form, 'vertical'); ?>
            </div>
        <?php } ?>
    </div>
    <?php if (!empty($config['sidetext']) || ($config['gmap_show'] && $config['gmap_position'] == 'side')) { ?>
        <div class="col-md-5">
            <?php if (!empty($config['sidetext'])) { ?>
                <div class="clearfix contact-sidetext">
                    <?php echo $config['sidetext']; ?>
                </div>
            <?php } ?>
            <?php if ($config['gmap_show'] && $config['gmap_position'] == 'side') { ?>
                <?php echo $this->googleMap($locations, $config['gmap_api_key'], 'point', $option); ?>
            <?php } ?>
        </div>
    <?php } ?>
    <?php if (!empty($config['bottomtext'])) { ?>
        <div class="clearfix contact-bottomtext col-md-12">
            <?php echo $config['bottomtext']; ?>
        </div>
    <?php } ?>
</div>