<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="contact">
    <?php if (!empty($config['toptext'])) { ?>
    <div class="top-text">
        <?php echo $config['toptext']; ?>
    </div>
    <?php } ?>
    <div class="row">
        <?php if (!empty($config['sidetext'])) {
            $class = 'col-md-6';
            $side = true;
        } else {
            $class = 'col-md-12';
            $side = false;
        } ?>
        <div class="<?php echo $class ?>">
        <?php if (!empty($config['finishtext'])) { ?>
            <div class="side-text">
            <?php echo $config['finishtext']; ?>
            </div>
        <?php } ?>
        </div>
        <?php if ($side) { ?>
        <div class="col-md-6">
            <div class="side-text">
            <?php echo $config['sidetext']; ?>
            </div>
        </div>
        <?php } ?>
    </div>
    <div class="side-social">
        <?php include $this->template('front/social'); ?>
    </div>
    <?php if (!empty($config['bottomtext'])) { ?>
    <div class="bottom-text">
        <?php echo $config['bottomtext']; ?>
    </div>
    <?php } ?>
</div>