<?php
$this->css($this->assetModule('css/front.css'));
// Load google map
if ($config['gmap_show']) {
    $locations = array(
        'latitude'  => $config['gmap_latitude'],
        'longitude' => $config['gmap_longitude'],
        'zoom'      => $config['gmap_zoon'],
        'title'     => $config['gmap_title'],
    );

    $option = array(
        'mapTypeId' => $config['gmap_type'],
    );
}
?>
<div class="clearfix">
    <?php if ($config['gmap_show'] && $config['gmap_position'] == 'top') { ?>
        <?php echo $this->googleMap($locations, $config['gmap_api_key'], 'point', $option); ?>
    <?php } ?>
    <?php if ($config['show_title']) { ?>
    <div class="page-header contact-title">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php } ?>
    <?php if (!empty($config['sidetext']) || ($config['gmap_show'] && $config['gmap_position'] == 'side')) {
        $class = 'col-md-7';
    } else {
        $class = 'col-md-12';
    } ?>
    <div class="<?php echo $class; ?>">
        <?php if (!empty($config['toptext'])) { ?>
        <div class="clearfix contact-toptext">
            <?php echo $config['toptext']; ?>
        </div>
        <?php } ?>
        <div class="contact-department-list">
            <div class="list-group">
                <?php foreach ($lists as $list) { ?>
                <a class="list-group-item" title="<?php echo $this->escape($list['title']); ?>" href="<?php echo $this->escape($list['url']);  ?>">
                    <?php echo $this->escape($list['title']); ?>
                </a>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php if (!empty($config['sidetext']) || ($config['gmap_show'] && $config['gmap_position'] == 'side')) { ?>
    <div class="col-md-5">
        <?php if (!empty($config['sidetext'])) { ?>
        <div class="clearfix contact-sidetext">
            <?php echo $config['sidetext']; ?>
        </div>
        <?php } ?>
        <?php if ($config['gmap_show'] && $config['gmap_position'] == 'side') { ?>
            <?php echo $this->googleMap($locations, $config['gmap_api_key'], 'point', $option); ?>
        <?php } ?>
    </div>
    <?php } ?>
    <?php if (!empty($config['bottomtext'])) { ?>
    <div class="clearfix contact-bottomtext col-md-12">
        <?php echo $config['bottomtext']; ?>
    </div>
    <?php } ?>
</div>