<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="contact">
    <h3><?php echo $this->escape($title); ?></h3>
    <?php if (!empty($config['toptext'])) { ?>
    <div class="top-text">
        <?php echo $config['toptext']; ?>
    </div>
    <?php } ?>
    <div class="row">
        <?php if (!empty($config['sidetext'])) {
            $class = 'col-md-6';
            $side = true;
        } else {
            $class = 'col-md-12';
            $side = false;
        } ?>
        <div class="<?php echo $class ?>">
            <div id="department-list">
                <ul>
                    <?php foreach ($lists as $list) { ?>
                    <li><a title="<?php echo $this->escape($list['title']); ?>" href="<?php echo $this->escape($list['url']);  ?>"><?php echo $this->escape($list['title']); ?></a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <?php if ($side) { ?>
        <div class="col-md-6">
            <div class="side-text">
            <?php echo $config['sidetext']; ?>
            </div>
        </div>
        <?php } ?>
    </div>
    <div class="side-social">
        <?php include $this->template('front/social'); ?>
    </div>
    <?php if (!empty($config['bottomtext'])) { ?>
    <div class="bottom-text">
        <?php echo $config['bottomtext']; ?>
    </div>
    <?php } ?>
</div>