<div id="social-items">
<?php if (!empty($config['social_twitter'])) { ?>
    <?php if(!empty($config['social_twitter_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_twitter_icon'], __('Twitter'));
    } else {
        $icon = '<i class="fa fa-twitter-square"></i>';
    } ?>
    <span id="social-twitter"><a rel="nofollow" title="<?php _e('Twitter') ?>" href="<?php echo $config['social_twitter']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_facebook'])) { ?>
    <?php if(!empty($config['social_facebook_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_facebook_icon'], __('Facebook'));
    } else {
        $icon = '<i class="fa fa-facebook-square"></i>';
    } ?>
    <span id="social-facebook"><a rel="nofollow" title="<?php _e('Facebook') ?>" href="<?php echo $config['social_facebook']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_google'])) { ?>
    <?php if(!empty($config['social_google_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_google_icon'], __('Google'));
    } else {
        $icon = '<i class="fa fa-google-plus-square"></i>';
    } ?>
    <span id="social-google"><a rel="nofollow" title="<?php _e('Google') ?>" href="<?php echo $config['social_google']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_youtube'])) { ?>
    <?php if(!empty($config['social_youtube_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_youtube_icon'], __('YouTube'));
    } else {
        $icon = '<i class="fa fa-youtube-square"></i>';
    } ?>
    <span id="social-youtube"><a rel="nofollow" title="<?php _e('YouTube') ?>" href="<?php echo $config['social_youtube']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_pinterest'])) { ?>
    <?php if(!empty($config['social_pinterest_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_pinterest_icon'], __('Pinterest'));
    } else {
        $icon = '<i class="fa fa-pinterest-square"></i>';
    } ?>
    <span id="social-pinterest"><a rel="nofollow" title="<?php _e('Pinterest') ?>" href="<?php echo $config['social_pinterest']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_instagram'])) { ?>
    <?php if(!empty($config['social_instagram_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_instagram_icon'], __('Instagram'));
    } else {
        $icon = '<i class="fa fa-instagram"></i>';
    } ?>
    <span id="social-instagram"><a rel="nofollow" title="<?php _e('Instagram') ?>" href="<?php echo $config['social_instagram']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_tumblr'])) { ?>
    <?php if(!empty($config['social_tumblr_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_tumblr_icon'], __('Tumblr'));
    } else {
        $icon = '<i class="fa fa-tumblr-square"></i>';
    } ?>
    <span id="social-tumblr"><a rel="nofollow" title="<?php _e('Tumblr') ?>" href="<?php echo $config['social_tumblr']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_trello'])) { ?>
    <?php if(!empty($config['social_trello_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_trello_icon'], __('Trello'));
    } else {
        $icon = '<i class="fa fa-trello"></i>';
    } ?>
    <span id="social-trello"><a rel="nofollow" title="<?php _e('Trello') ?>" href="<?php echo $config['social_trello']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_linkedin'])) { ?>
    <?php if(!empty($config['social_linkedin_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_linkedin_icon'], __('LinkedIn'));
    } else {
        $icon = '<i class="fa fa-linkedin-square"></i>';
    } ?>
    <span id="social-linkedin"><a rel="nofollow" title="<?php _e('LinkedIn') ?>" href="<?php echo $config['social_linkedin']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
<?php if (!empty($config['social_github'])) { ?>
    <?php if(!empty($config['social_github_icon'])) {
        $icon = sprintf('<img src="%s" alt="%s" />', $config['social_github_icon'], __('Github'));
    } else {
        $icon = '<i class="fa fa-github-alt"></i>';
    } ?>
    <span id="social-github"><a rel="nofollow" title="<?php _e('Github') ?>" href="<?php echo $config['social_github']; ?>"><?php echo $icon; ?></a></span>
<?php } ?>
</div>